-- CreateTable
CREATE TABLE "gnomon_V" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "x_V" REAL NOT NULL,
    "y_V" REAL NOT NULL,
    "z_V" REAL NOT NULL,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "gnomon_R" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "x_R" REAL NOT NULL,
    "y_R" REAL NOT NULL,
    "z_R" REAL NOT NULL,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "calc_Dados" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "x_Calc" REAL NOT NULL,
    "y_Calc" REAL NOT NULL,
    "z_Calc" REAL NOT NULL,
    "date_Calc" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
