class Calc{
	constructor(long, lat){
		this.longitude = long;
		this.latitude = lat;
	}

	Nascer_Sol(){
		//this.setDia_ano(4);
        function conv_Grau(){
        	document.write("oi").innertext;
            //return (grau * (Math.PI/180));
        }

		//document.write(this.getDia_ano()).innertext;
		document.write("I").innertext;
		document.write(conv_Grau()).innertext;
	}

	/*
    getDia_ano(){
        return this.dia_ano;
    }
    setDia_ano(x){
        this.dia_ano = x;
    }*/
}